WebApplication1/Controllers/AjaxController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    public class DataModel
    {
        public int Id {get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }

    public class AjaxController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult SaveData(DataModel model)
        {
            return View("_DataSaved", model);
        }

        public object GetData()
        {
            var obj = new {Eins = 1, Zwei = 2, Drei = 3, Vier = 4};
            return obj;
        }
    }
}

WebApplication1/Controllers/AuthorizedController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    public class AuthorizedController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            return Content($"Authorized as {User.Identity.Name}");
        }

        [Authorize(Policy = "SqlServerJobViewer")]
        public IActionResult SqlServerJobViewer()
        {
            return Content($"Sql Server JobViewer: Authorized as {User.Identity.Name}");
        }
    }
}

WebApplication1/Controllers/ExcelExportController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;

namespace MinimalExample.Controllers
{
    public class MyData
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Dezimal { get; set; }
    }

    [Produces("application/json")]
        [Route("api/ExcelExport")]
        public class ExcelExportController : Controller
        {
            public IActionResult GetExcelFile()
            {
                var data = new List<MyData>
                {
                    new MyData {Id = 1, Name =" Eins", Dezimal = 12.55M},
                    new MyData {Id = 2, Name =" Zwei", Dezimal = 1313.3443M},
                };
                var pck = new ExcelPackage();
                var ws = pck.Workbook.Worksheets.Add("Content");


                ws.Cells["A1"].LoadFromCollection(data);

                return File(pck.GetAsByteArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", $"Qualitaetsberichte-Export - {DateTime.Now.ToLongDateString()}.xlsx");

            }
        }
    
}

WebApplication1/Controllers/HomeController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    public class MyModel
    {
        public int Number { get; set; }
        public string Text { get; set; }
        public List<string> StringListe { get; set; }
    }

    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var model = new MyModel
            {
                Number = 1,
                Text = "Hallo",
                StringListe = new List<string> {"eins", "zwei", "drei"} //wird nur in der Partial View verwendet
            };
            return View(model);
        }

        public IActionResult GetList()
        {
            //Partial Views können auch "ganz normal" zurückgegeben werden bspw. für einen AJAX-Request
            var model = new List<string>();
            return View("_ListPartial", model);
        }
    }
}

WebApplication1/Controllers/ValuesController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Data;

namespace WebApplication1.Controllers
{
    [Route("api/[controller]")]
    public class ValuesController : Controller
    {
        private readonly TestContext _db;

        public ValuesController(TestContext db)
        {
            _db = db;
        }

        // GET api/values
        [HttpGet]
        public IEnumerable<MyEntity> Get()
        {
            return _db.MyEntities.ToList();
        }
    }
}

WebApplication1/Views/Ajax/Index.cshtml
@model WebApplication1.Controllers.DataModel
@{
    Layout = "_Layout";
}

<h1>Ajax Form</h1>

<div>
    @*Diese Form wird per Ajax abgesendet und das Ergebnis in das div mit der Id = result geladen
        "Unterstützt" wird das durch jquery-unobtrusive-ajax.js
    *@
    <form asp-action="SaveData" asp-controller="Ajax" data-ajax="true" data-ajax-method="post" data-ajax-update="#result">
        <input asp-for="Id" type="hidden" />
        <input asp-for="Name" />
        <input asp-for="Description" />
        <button type="submit">Senden</button>
    </form>
</div>

<div id="result">
    Hier wird das Ergebnis angezeigt...
</div>

<div style="margin-top: 30px;">
    <button data-command="getData" data-url="@Url.Action("GetData")">Daten via Ajax holen ohne Form</button>
    <div id="data">
        <div id="eins"></div>
        <div id="zwei"></div>
    </div>
</div>

@section scripts {

    <script src="~/scripts/app/ajaxmodule.js"></script>
}

WebApplication1/Views/Ajax/_DataSaved.cshtml
@model WebApplication1.Controllers.DataModel
@{
    Layout = null;
}

<h1>Result</h1>

<div>
    <ul>
        <li>Name => @Model.Name</li>
        <li>Description => @Model.Description</li>
        <li>Zeit => @DateTime.Now.ToLongTimeString()</li>
    </ul>
</div>

WebApplication1/Views/Home/Index.cshtml
@model WebApplication1.Controllers.MyModel
@{
    Layout = "_Layout";
}

<h1>@Model.Text - @Model.Number</h1>

<div>
    @Html.Partial("_ListPartial", Model.StringListe)
</div>

WebApplication1/Views/Home/_ListPartial.cshtml
@model List<string>
@{
    Layout = null; //Layout = null, da sonst alles aus _Layout dupliziert wird
}

<ul>
    @foreach (var item in Model)
    {
        <li>@item</li>
    }
</ul>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>

    <script src="~/scripts/lib/jquery/dist/jquery-3.1.1.min.js"></script>
    <script src="~/scripts/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>